on:
  pull_request:
  push:
    branches: [main]
jobs:
  eval:
    strategy:
      matrix:
        names: [aarch64-linux, aarch64-linux-minimal]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: Do a first pass do download deps
        run: nix path-info --derivation .#nixosConfigurations.${{ matrix.names }}.foo.config.system.build.toplevel  --no-eval-cache
      - name: Benchmark eval time
        run: perf -r10 stat nix path-info --derivation .#nixosConfigurations.${{ matrix.names }}.foo.config.system.build.toplevel  --no-eval-cache
      - name: Build
        run: nix build .#nixosConfigurations.${{ matrix.names }}.foo.config.system.build.toplevel
