on:
  pull_request:
  push:
    branches: [main]
jobs:
  eval:
    strategy:
      matrix:
        nixosConfigurations: [aarch64-linux, aarch64-linux-minimal]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: Benchmark eval time
        run: nix run nixpkgs#hyperfine -- 'nix path-info --derivation .#nixosConfigurations.${{ matrix.nixosConfigurations }}.config.system.build.toplevel --no-eval-cache'
      - name: Build
        run: nix build .#nixosConfigurations.${{ matrix.nixosConfigurations }}.config.system.build.toplevel
